### ISSUE TITLE
Update Trace Reader for PIM Ops

### ISSUE THREAD

**Issue by bfmorri3** [Pitt-JonesLab/RTSim#5]
We want to update the trace reader to enable parsing of non-R/W commands

**Comment by bfmorri3** [comment]
PIM Operations
Row Clone
2 operands(src, dest)
Shift
2 operand(addr, dir)
Transverse Write
3 operands(addr, dir, value)
Transverse Read
1 operand(addr)
Traces
R/W
\<Cycle\> \<Op\> [\<addr\> \<data\>] \<thread\>
Row clone
\<Cycle\> \<Op\> [\<src_addr\> \<dest_addr\>] \<thread\>
Shift
\<Cycle\> \<Op\> [\<addr\> \<dir\>] \<thread\>

**Comment by bfmorri3** [comment]
Todo: where to set transverse distance config

**Comment by pbrazzle-old** [comment]
9/7 Meeting trace line format:

\<Cycle\> \<Op\> \<src_addr\> \<dest_addr\> \<row_data\> \<thread\>

Opcodes:
TR, TW, (Shift?), Rowclone, (AND, OR, XOR?)
